#!/bin/sh
set -x
./configure\
    --with-tcl=$(brew --prefix tcl-tk)\
    --with-tk=$(brew --prefix tcl-tk)\
    --with-cairo=$(brew --prefix cairo)/include\
    "PYTHON3=$(brew --prefix python3)/bin/python3"\
    "LDFLAGS=-L$(brew --prefix cairo)/lib"
